spring.application.name=RevShop_P2

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=revshop_p2
spring.datasource.password=revshop
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false

server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123

jwt.secret=revshopsecretkeyrevshopsecretkey
jwt.expiration=86400000